<!--
**************
This file is a modified version of a page from the previous CALS Research Division Site located at http://www.cals.wisc.edu/Research/staff/index.php , which pulls staff contact information from a database that resides on the CALS web server. HTML and CSS were edited to mimic the appearance of the current Research Division site, scripts were left unaltered. 

IMPORTANT! This page relies on Dreamweaver Spry; Spry javascript library files are required and all Collapsible Panel/Collapsible Tab ids and classes must be edited carefully.

also IMPORTANT! menus, header, footer etc on this page mimic content that is pulled dynamically on pages that are managed through Wordpress. When these items are updated via the Wordpress dashboard, they must be manually updated on this page. The simplest way to do this is to copy and paste the source code generated by one of the Wordpress-managed pages

Liz Krznarich 11/20/2012
***************
-->

<?php include 'http://www.cals.wisc.edu/Research/staff/connect-test.php';?>

<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>CALS Research Division &gt; Proposal Development Contacts</title>

<!--Dreamweaver Spry scripts and styles from original file-->
<script src="../scripts/spry/SpryCollapsiblePanel.js" type="text/javascript"></script>
<script src="../scripts/javascript/toggleOthers.js" type="text/javascript"></script>
<script src="../scripts/javascript/gettab.js" type="text/javascript"></script>
<script src="../scripts/spry/SpryTabbedPanels.js" type="text/javascript"></script>

<script type="text/javascript" src="handlePanel.js" />
<script src="../scripts/javascript/toggleOthers.js" type="text/javascript"></script>
<script type="text/javascript">
function closePanels(parentID) {
	var status = parentID.isOpen(); 
	if (!status) {
		for (panel = 1; panel<=95; panel++) {
			var panelname = "CollapsiblePanel"+panel;
			var panelobj = eval(panelname);
			if (panelobj != parentID) panelobj.close();
		}
	}
}
</script>
<!--End Dreamweaver Spry scripts-->

<!--Wordpress styles and link relations from CALS Research Working theme-->
<link rel="profile" href="http://gmpg.org/xfn/11" />
<link rel="stylesheet" type="text/css" media="all" href="http://research.cals.wisc.edu/wp-content/themes/cals_research_working/style.css" />
<link rel="pingback" href="http://research.cals.wisc.edu/xmlrpc.php" />
<link rel="shortcut icon" href="http://research.cals.wisc.edu/wp-content/themes/cals_research_working/favicon.ico" />
<link rel="alternate" type="application/rss+xml" title="CALS Research Division &raquo; Feed" href="http://research.cals.wisc.edu/feed/" />
<link rel="alternate" type="application/rss+xml" title="CALS Research Division &raquo; Comments Feed" href="http://research.cals.wisc.edu/comments/feed/" />
<meta property="og:image" content="http://news.cals.wisc.edu/wp-content/uploads/2010/08/Agricult_Hall_college1_00-75x75.jpg"/>
<!--End Wordpress styles and link relations-->

<!--Modified Dreamweaver stylesheet - EDIT THIS ONE!-->
<link href="../css/tabbed-panels-wp-mimic.css" rel="stylesheet" type="text/css" />
</head>

<!--Begin HTML copied and pasted from Wordpress output-->
<body onLoad="gettab()" class="page page-id-60 page-parent page-template-default">

<div id="pre-wrapper">
<div id="wrapper" class="hfeed">
    <div id="header">
		<div id="masthead">
        	
            <div class="utility" role="navigation">
				<div class="menu-utility"><ul id="menu-utilities" class="menu"><li id="menu-item-64" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-64"><a href="http://research.cals.wisc.edu/">Home</a></li>
<li id="menu-item-2261" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2261"><a href="http://research.cals.wisc.edu/sample-page/our-mission/">About</a></li>
<li id="menu-item-58" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-58"><a href="http://research.cals.wisc.edu/contact-us/">Contact Us</a></li>
<li id="menu-item-63" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-60 current_page_item menu-item-63"><a href="http://research.cals.wisc.edu/staff/">Staff Directory</a></li>
<li id="menu-item-1750" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1750"><a href="http://research.cals.wisc.edu/events/">Events</a></li>
</ul></div>            </div>
			
            <div id="branding" role="banner">
				<h1 id="site-title">
					<span>
						<a href="http://research.cals.wisc.edu/" title="CALS Research Division" rel="home">CALS Research Division</a>
					</span>
				</h1>
				<div id="site-description">UW-Madison</div>
 
<!--										<img src="http://research.cals.wisc.edu/files/2012/10/cals_research_logo1.png" width="417" height="101" alt="" />
					-->
 
                <div id="logo">
                    <a href="http://research.cals.wisc.edu/" title="CALS Research Division" rel="home"><img src="http://research.cals.wisc.edu/files/2012/10/cals_research_logo1.png" width="417" height="101" alt="CALS Research Division" /></a>
                </div><!-- #logo -->  
                                  
			</div><!-- #branding -->
 
            <div id="search">
                <form role="search" method="get" id="searchform" action="http://research.cals.wisc.edu/" >
	<div><label class="screen-reader-text" for="s">Search for:</label>
	<input type="text" value="Enter your search keywords here..." name="s" id="s" />
	<input type="image" src="http://research.cals.wisc.edu/wp-content/themes/cals_research/images/cals_searchbutton.png" id="searchsubmit" value="Search" />
	</div>
	</form>            </div><!-- #search -->
 
			<div id="access" role="navigation">
			  				<div class="skip-link screen-reader-text"><a href="#content" title="Skip to content">Skip to content</a></div>
								<div class="menu-header"><ul id="menu-mainnav" class="menu"><li id="menu-item-652" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-652"><a href="http://research.cals.wisc.edu/proposals-agreements/news-updates/">Proposals &#038; Agreements</a>
<ul class="sub-menu">
	<li id="menu-item-561" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-561"><a href="http://research.cals.wisc.edu/proposals-agreements/news-updates/">News &#038; Updates</a></li>
	<li id="menu-item-335" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-335"><a href="http://research.cals.wisc.edu/proposals-agreements/development/budget-building/">Development</a></li>
	<li id="menu-item-689" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-689"><a href="http://research.cals.wisc.edu/proposals-agreements/submission/submission-process/">Submission</a></li>
	<li id="menu-item-336" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-336"><a href="http://research.cals.wisc.edu/proposals-agreements/agreements/material-transfer-agreements/">Agreements</a></li>
</ul>
</li>
<li id="menu-item-653" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-653"><a href="http://research.cals.wisc.edu/compliance/news-updates/">Compliance</a>
<ul class="sub-menu">
	<li id="menu-item-2254" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2254"><a href="http://research.cals.wisc.edu/compliance/news-updates/">News &#038; Updates</a></li>
	<li id="menu-item-687" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-687"><a href="http://research.cals.wisc.edu/compliance/research-protocols/animal-use/">Research Protocols</a></li>
	<li id="menu-item-688" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-688"><a href="http://research.cals.wisc.edu/compliance/regulatory-compliance/outside-activities-reports/">Regulatory Compliance</a></li>
</ul>
</li>
<li id="menu-item-780" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-780"><a href="http://research.cals.wisc.edu/awardgift-management/awardgift-monitoring/">Award/Gift Management</a>
<ul class="sub-menu">
	<li id="menu-item-155" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-155"><a href="http://research.cals.wisc.edu/awardgift-management/awardgift-monitoring/">Award/Gift Monitoring</a></li>
	<li id="menu-item-942" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-942"><a href="http://research.cals.wisc.edu/awardgift-management/policies/audits/">Policies</a></li>
	<li id="menu-item-167" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-167"><a href="http://research.cals.wisc.edu/awardgift-management/faqs/">Award Management FAQs</a></li>
</ul>
</li>
<li id="menu-item-779" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-779"><a href="http://research.cals.wisc.edu/funding-opportunities/">Funding Opportunities</a>
<ul class="sub-menu">
	<li id="menu-item-2252" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2252"><a href="http://research.cals.wisc.edu/funding-opportunities/">Current Calls for Proposals</a></li>
	<li id="menu-item-782" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-782"><a href="http://research.cals.wisc.edu/funding-opportunities/federal/grants-gov/">Federal</a></li>
	<li id="menu-item-238" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-238"><a href="http://research.cals.wisc.edu/funding-opportunities/non-federal/">Non-Federal</a></li>
	<li id="menu-item-783" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-783"><a href="http://research.cals.wisc.edu/funding-opportunities/training-grants-fellowships/nih-training-grants/">Training Grants &#038; Fellowships</a></li>
	<li id="menu-item-784" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-784"><a href="http://research.cals.wisc.edu/funding-opportunities/cals/wisconsin-distinguished-graduate-fellowships/">CALS</a></li>
</ul>
</li>
<li id="menu-item-781" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-781"><a href="http://research.cals.wisc.edu/resources-training/acronyms/">Resources &#038; Training</a>
<ul class="sub-menu">
	<li id="menu-item-1729" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1729"><a href="http://research.cals.wisc.edu/resources-training/acronyms/">Acronyms</a></li>
	<li id="menu-item-1731" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1731"><a href="http://research.cals.wisc.edu/resources-training/definitions/">Definitions</a></li>
	<li id="menu-item-272" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-272"><a href="http://research.cals.wisc.edu/resources-training/how-to/">How-To (FAQ)</a></li>
	<li id="menu-item-785" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-785"><a href="http://research.cals.wisc.edu/resources-training/training/cals-training-opportunities/">Training</a></li>
	<li id="menu-item-787" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-787"><a href="http://research.cals.wisc.edu/resources-training/cals-financial-networking-group/">CALS Financial Networking Group</a></li>
	<li id="menu-item-284" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-284"><a href="http://research.cals.wisc.edu/resources-training/policies-and-procedures/">Policies and Procedures</a></li>
	<li id="menu-item-285" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-285"><a href="http://research.cals.wisc.edu/resources-training/rsp-data-searches/">RSP Data Searches</a></li>
</ul>
</li>
</ul></div>			</div><!-- #access -->
		</div><!-- #masthead -->
	</div><!-- #header -->

<div id="main">
 
		<div id="secondary" class="widget-area" role="complementary">
			<ul class="xoxo">
				<li id="nav_menu-11" class="widget-container widget_nav_menu"><h3 class="widget-title">Staff Directory</h3><div class="menu-staffdirectory-container"><ul id="menu-staffdirectory" class="menu"><li id="menu-item-2262" class="news-updates menu-item menu-item-type-post_type menu-item-object-page page_item page-item-60 current_page_item menu-item-2262"><a href="http://research.cals.wisc.edu/staff/">Staff Directory</a></li>
<li id="menu-item-2333" class="news-updates menu-item menu-item-type-custom menu-item-object-custom menu-item-2333"><a href="http://www.cals.wisc.edu/Research/staff/proposal-contacts.php">Proposal Development Contacts by Department</a></li>
<li id="menu-item-2334" class="news-updates menu-item menu-item-type-custom menu-item-object-custom current-menu-item menu-item-2334"><a href="http://www.cals.wisc.edu/Research/staff/other-functions.php">Staff Contacts by Function</a></li>
<li id="menu-item-2367" class="news-updates menu-item menu-item-type-post_type menu-item-object-page menu-item-2367">
<a href="http://research.cals.wisc.edu/staff/administration-directory/">Administration Directory</a>
</li>
</ul></div></li>			</ul>
		</div><!-- #secondary .widget-area -->
 
 
		<div id="container">
			<div id="content" role="main">
    
  <div id="TabbedPanels1" class="TabbedPanels">
            <ul class="TabbedPanelsTabGroup">
                <li class="TabbedPanelsTab" tabindex="0">Staff Contacts by Function</li>
            </ul>
    <div class="TabbedPanelsContentGroup">

   <div class="TabbedPanelsContent" style="overflow:auto; width:100%; display: none;">
  
                    <p>Select a function to see which staff member is the primary contact.</p>
     
                   <?php	 
                    //QUERY
                    $query = "SELECT functions.function, functions.ID, FunctionMap.funcID, FunctionMap.primary, FunctionMap.back1, FunctionMap.back2 FROM functions INNER JOIN FunctionMap ON FunctionMap.funcID = functions.ID ORDER BY functions.function";
                    
                    //SET QUERY to VARIABLE
                    $result = mysql_query($query);
                    
                    //SET ERROR to VARIABLE
                    $error = mysql_error() ;
                     
                     //PRINTS ERROR IF ANY ERRORS
                     print ($error);
                     //FETCHING RESULTS
			for ($q=1; $q<96; $q++)
				{                   
					 while ($row = mysql_fetch_array($result))
					{
					//SET table column values TO VARIABLE
						$functionName = $row['function'];
						$functionID = $row['ID'];
						$mapFunctionID = $row['funcID'];
						$p = $row['primary'];
						$b1 = $row['back1'];
						$b2 = $row['back2'];
						
				?>							
		
		      <div class="CollapsiblePanel" id="CollapsiblePanel<?php echo $q ?>">
				<div class="CollapsiblePanelTab" tabindex="0" onClick="closePanels(CollapsiblePanel<?php echo $q ?>)">
					<input type="hidden" name="funcs" onClick="CollapsiblePanel<?php echo $q ?>.open(CollapsiblePanel<?php echo $q ?>)">
						<?php echo $functionName ?>	
                </div>
                <div class="CollapsiblePanelContent">
                
                                  <?php 
				  		echo '<table width="500" cellpadding="3">' . "\n";
						echo "<tr>\n";
						echo "<td>&nbsp;</td>\n";
						echo '<td><font size="2"><b><u>Primary Contact</u></b></font></td>' . "\n";
						echo '<td><font size="2"><b><u>Back-up Contacts</u></b></font></td>' . "\n";
						echo "</tr>\n";
						
					//	echo "<tr><td colspan=3>&nbsp</td></tr>\n";
						
						echo '<tr valign="top">' . "\n";
						echo '<td>&nbsp</td>' . "\n";
						echo "<td>" . format_person_other_functions($p, $mapFunctionID) . "</td>\n";
						echo "<td>" . format_person_other_functions($b1, $mapFunctionID). '<br /><br />' . format_person_other_functions($b2, $mapFunctionID) . "</td>\n";
						echo "</tr>\n";
						
						echo "</table>\n";
						
					?>
                        
			    </div>
		       </div>             
                    <?php break; }  } ?>
				  </div>	
            
      
     
    </div><!--.TabbedPanelsContentGroup-->
  </div><!--#TabbedPanels1-->


  <script type="text/javascript">
<!--
var TabbedPanels1 = new Spry.Widget.TabbedPanels("TabbedPanels1");
<?php 
for ($i=1; $i<96; $i++)
{
echo 'var CollapsiblePanel'.$i.' = new Spry.Widget.CollapsiblePanel("CollapsiblePanel'.$i.'", {contentIsOpen:false, enableAnimation:false,enableKeyboardNavigation:true});';
}
?>
//-->
</script>
 <!--End code from previous Research Div site-->
 
 
 <!--Begin HTML copied and pasted from Wordpress output-->   
<div id="comments">
 
 
	<p class="nocomments">Comments are closed.</p>
 
 
								
</div><!-- #comments -->
                
 
			</div><!-- #content -->
		</div><!-- #container -->
 
 
	</div><!-- #main -->
 
 
	
    <div id="footer" role="contentinfo">
		<div id="colophon">
                <div class="utility" role="navigation">
                    <div class="menu-utility"><ul id="menu-utilities-1" class="menu"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-64"><a href="http://research.cals.wisc.edu/">Home</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2261"><a href="http://research.cals.wisc.edu/sample-page/our-mission/">About</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-58"><a href="http://research.cals.wisc.edu/contact-us/">Contact Us</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-60 current_page_item menu-item-63"><a href="http://research.cals.wisc.edu/staff/">Staff Directory</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1750"><a href="http://research.cals.wisc.edu/events/">Events</a></li>
</ul></div>                </div>
 
                <div id="copywrong">
                	<p>&copy; Copyright 2012.&nbsp;All rights reserved.
                    <a href="http://www.cals.wisc.edu">College of Agricultural and Life Sciences</a> - <a href="http://www.wisc.edu" target="_blank">University of Wisconsin-Madison</a><br />
                    Website feedback, questions or accessibiity issues: <a href="mailto:ekrznarich@cals.wisc.edu">Contact the Webmaster</a></p>
                </div> <!-- #copywrong -->
 
		</div><!-- #colophon -->
	</div><!-- #footer -->
 
</div><!-- #wrapper -->
</div><!-- #pre-wrapper -->
	
<script type="text/javascript"> 
	//clear CALS searchbox on click if value = 'Enter your search keywords here...'
	jQuery('#s,#q').click(function(){
		if(this.value=='Enter your search keywords here...' || this.value=='Enter keywords or name here...') { this.value='';}
	});
</script>
<script type='text/javascript' src='http://research.cals.wisc.edu/wp-content/themes/cals_research/library/scripts/js/slides.min.jquery.js?ver=3.4.1'></script>
<script type='text/javascript' src='http://research.cals.wisc.edu/wp-content/themes/cals_research/library/scripts/js/jquery.idtabs.min.js?ver=3.4.1'></script>
<script type='text/javascript' src='http://lite.piclens.com/current/piclens_optimized.js?ver=3.4.1'></script>
<script type='text/javascript' src='http://research.cals.wisc.edu/wp-includes/js/jquery/jquery.form.js?ver=2.73'></script>
</body>
</html>
<!-- This Quick Cache file was built for (  research.cals.wisc.edu/staff/ ) in 0.52100 seconds, on Nov 15th, 2012 at 8:19 pm UTC. -->
<!-- This Quick Cache file will automatically expire ( and be re-built automatically ) on Nov 15th, 2012 at 9:19 pm UTC -->

</body>
</html>
<!--End HTML copied and pasted from Wordpress output-->